name: Build project

on:
  workflow_dispatch:
  push:
    branches:
      - master # Set a branch name to trigger deployment
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: "zkoppert/innersource-crawler"
          path: "innersource-crawler"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.0
      - name: Install dependencies
        run: |
          cd innersource-crawler
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build env file
        run: |
          echo "\n\n" > innersource-crawler/.env
          cat << EOF > innersource-crawler/.env
          GH_TOKEN='${{ secrets.ADMIN_TOKEN}}'
          ORGANIZATION='nextgen-ealogy'
          TOPIC='inner-source'
          EOF
      - name: Generate repos file
        run: |
          cd innersource-crawler
          python ./crawler.py
          touch repos.json
          mv repos.json ../data/repos.json
      - name: Build Website
        run: |
          mkdir css
          npm i
          npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          folder: ./_site
          branch: gh-pages
